version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - CONNECTION_URL=mongodb://mongo:27017/products-project
      - PORT=8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
